<?php require('template/header.phtml'); ?>
<!--HTML for contacting about using a charge point-->
<div class="container-fluid">
    <?php if($view->enquire) :?>
    <form method="post" action=" ">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Email</label>
                <input type="email" class="form-control" id="inputEmail4" value="<?php $view->email?>">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label>Address</label>
            <input type="text" class="form-control" id="inputAddress" value="<?php $view->address ?>">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>City</label>
                <input type="text" class="form-control" id="inputCity" value="<?php $view->city ?>">
            </div>
            <div class="form-group col-md-4">
                <label>Postcode</label>
                <input type="text" class="form-control" id="inputPostcode" value="<?php $view->postcode ?>">
            </div>
            <div class="form-group col-md-2">
                <label>Booking Date</label>
                <input type="date" class="form-control" id="inputDate">
            </div>
            <div class="form-group col-md-2">
                <div class="input-group col-mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">£perHour</span>
                    </div>
                    <input type="text" class="form-control" name="cost" value="<?php $view->cost ?>">
                </div>
            </div>
        </div>
        <button name="sendBtn" type="submit" class="btn btn-outline-success">Send</button>
    </form>
    <?php endif;?>
    <br>
    <br>
    <br>
    <br>
</div>
<?php require('template/footer.phtml') ?>
