<?php require('template/header.phtml') ?>
<!--HTML for register-->
<!--displays error message if issue with registering(error is true)-->
<?php if($view->error){
    echo '<h4 id="errorMsg">' . $view->errorMsg . '</h4>';
} ?>
<!--form for inputting data for new user-->
<form method="post" action=" " enctype="multipart/form-data">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label>Full Name</label>
            <input type="text" class="form-control" id="inputName" placeholder="Full name" name="fullname">
        </div>
        <div class="form-group col-md-6">
            <label>Email</label>
            <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="username">
        </div>
        <div class="form-group col-md-6">
            <label>Password</label>
            <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="password">
        </div>
        <div class="form-group col-md-6">
            <label for="formFile" class="form-label">Profile Picture</label>
            <input type="file" class="form-control" name="profilePic" id="formFile">
        </div>
    </div>
    <input name="signUpBtn" value="Sign Up" type="submit" class="btn btn-outline-success btn-block mb-4" id="signUpBtn"/>
</form>
<br>
<br>
<br>
<br>
<?php require('template/footer.phtml') ?>
