<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="/css/my-style.css" rel="stylesheet">

    <!--Leaflet stylesheet-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="">

    <title>Green Point - <?php echo $view->pageTitle; ?></title>
</head>


< class="d-flex flex-column h-100">

<!--<body role=""document"> -->


<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Green Point <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="chartreuse" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                </svg></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="index.php">Home</a>
                    </li>
                    <?php if(!$view->display): ?>
                        <li class="nav-item">
                            <a class="nav-link" href="addChargePoint.php">Add Charge Point</a>
                        </li>
                    <?php endif; ?>
                </ul>
                <?php if($view->display): ?>
                    <ul class="navbar-nav me-auto mb-3 mb-md-0">
                        <li class="nav-item">
                            <div class="dropdown">
                                <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside" id="dropdownBtn">
                                    Log In
                                </button>
                                <form class="dropdown-menu p-3" method="post" action=" ">
                                    <div class="mb-3">
                                        <label class="form-label">Username: </label>
                                        <input type="email" name="username" class="form-control" placeholder="email@example.com">
                                    </div>
                                    <div class="mb-3">
                                        <label class="mb-3">Password: </label>
                                        <input type="password" name="password" class="form-control" placeholder="password">
                                    </div>
                                    <input name="signInBtn" value="Sign In" type="submit" class="btn btn-block mb-4" id="signInBtn"/>
                                </form>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="btn" href="register.php" id="registerBtn"> Register </a>
                        </li>
                    </ul>
                <?php else: ?>
                    <ul class="navbar-nav me-auto mb-3 mb-md-0">
                        <li class="nav-item">
                            <form action=" " method="post">
                                <div class="col-md-4">
                                    <input type="submit" value="Sign out" name="signOutBtn" class="btn btn-danger"/>
                                </div>
                            </form>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
    </nav>
</header>
<!-- Begin page content -->
<main class="flex-shrink-0">

    <div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <h1><?php echo $view->pageTitle; ?></h1>
                <!-- https://getbootstrap.com/docs/5.2/examples/sticky-footer-navbar/ -->
            </div>
        </div>

        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-10">
